site_name: DevOps Learning Notes - Srikanth Velma
site_url: https://velmasrikanth.github.io/Devops-Learning/
repo_url: https://github.com/velmasrikanth/Devops-Learning
repo_name: GitHub Repository
edit_uri: edit/main/docs/ # Allows users to click 'Edit' and go straight to the Markdown file


# The Material for MkDocs Theme (Responsible for colors and layout)
theme:
  name: material
  palette:
    # Set to a dark color scheme for a modern, code-friendly look
    scheme: slate 
    primary: indigo
    accent: deep orange
  features:
    - content.tabs.link
    - navigation.expand
    - search.suggest
    - search.highlight
    - toc.integrate # Puts the Table of Contents right next to the content
    - header.autohide

# Enable Extra Markdown Features (The "alloptions" for content)
markdown_extensions:
  - admonition # Allows color boxes for notes/warnings
  - codehilite # Required for proper syntax highlighting
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox

# Site Navigation (Maps to the files in the 'docs/' folder)
nav:
  - Home: index.md
  - üê≥ Docker Fundamentals:
    - 01. Docker Basics: docker/01-docker-basics.md
    - 02. Docker Installation: docker/02-docker-installation.md
    - 03. DockerFile: docker/03-dockerfile.md

  - ‚òÅÔ∏è Kode kloud 100 Days:
    - 01. Azure Cloud-100 Days: kodekloud/01-100days-azure.md
   

  - ‚ò∏Ô∏è Kubernetes Deep Dive:
    - 01. Deployments: kubernetes/01-deployment.md
    - 02. Services & Ingress: kubernetes/02-services.md
  - CI/CD & Automation: automation.md